// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Props2JsonExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Props2JsonExtension.a141ffba-6c41-4076-9e71-01082fd2559b";
        public const string Name = "Props2JsonExtension";
        public const string Description = @"Plain and simple, straight to the point JSON extractor from its properties and types.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Deivid Rodrigues";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
